[feat] Add QR Code Scanning Functionality
SaltyCucumber/assets-portal pull request #104
Opened 2023-08-08 18:12 UTC by hummusonrails

Add the ability to scan a recipient wallet address for a new NFT minting via QR code

2023-08-09 11:39 UTC, SaltyCucumber reviewed
I'll check the solution itself a bit later, having calls today
but for now these are the changes I'd like to see

2023-08-09 11:39 UTC, SaltyCucumber commented on package-lock.json
This shouldn't be pushed, because yarn is used for packages

2023-08-09 11:39 UTC, SaltyCucumber commented on package.json
> +    "react-zxing": "^1.1.4",
need exact version
yarn add react-zxing@1.1.4 -E

2023-08-09 11:39 UTC, SaltyCucumber commented on src/components/Pages/MyAssets/MintNft/MintNft.tsx
> -
Please leave these new lines,
yarn format does the job automatically for this part
but the ones in HTML below were done manually by me for clarity, I like to separate blocks visually, so leave them be

2023-08-09 16:18 UTC, SaltyCucumber requested changes
So some changes need to be done:
1. react-zxing is requiring specific node versions, 16 or 18, I'm using 20 right now, so I need a "hack" for this `yarn install --ignore-engines`, so either the lib itself should be updated to not have this limit or some other lib should be used instead.
2. UX improvements: 
a. A QR code icon can be placed next to the "Mint to" input or label
b. On click of that icon, a modal should appear (use modal from react-bootstrap, like other modals in the portal)
c. Said modal should only have the QR scanner in it and nothing else
d. On successful scan modal should close automatically and the wallet address should appear in the input

2023-08-09 16:41 UTC, hummusonrails commented
> So some changes need to be done...

Thanks, I'll work on incorporating those changes

2023-08-10 16:03 UTC, hummusonrails commented
@SaltyCucumber, could use your help when you have a moment.

I refactored the QR code scanning integration to incorporate all the requested UX improvements. I needed to shift to a new package that worked better in a modal than the original one I chose. 

However, I'm experiencing a `tsc` linting error for the `new` constructor of the `QrScanner`, even though the `QrScanner` types definition in `node_modules` seems to define it.

Specifically, seeing the following error:

```
src/components/Modals/QrScanner/QrScanner.tsx:36:27 - error TS2351: This expression is not constructable.
  Type 'typeof import("/Dev/nft-portal/node_modules/qr-scanner/types/qr-scanner")' has no construct signatures.

36     const qrScanner = new QrScanner(
                             ~~~~~~~~
Found 1 error in src/components/Modals/QrScanner/QrScanner.tsx:36
```

I've tried to explicitly add the types file to the config, but that doesn't seem to work.

Besides this issue, everything from a usability perspective is working as requested.

2023-08-11 18:41 UTC, SaltyCucumber commented
Unfortunately the lib confuses typescript a bit, so I used "any" in this case. And refactored the code.

2023-08-11 18:52 UTC, SaltyCucumber approved these changes

2023-08-11 19:01 UTC, merged